import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body
    className="text-dark-charcoal max-w-7xl mx-auto"
    style={{
      background: "linear-gradient(to right, #FEE715 80%, #FEE715 80%)", // Adjust gradient proportions
      color: "#101820", // Default text color
    }}
  >
    <main
      className="bg-dark-charcoal/90 shadow-2xl drop-shadow-2xl text-bright-yellow"
      style={{
        backgroundColor: "#101820", // Dark Charcoal background for main content
        color: "#FEE715", // Bright Yellow text
      }}
    >
      <Header />
      {children}
    </main>
  </body>
</html>






  );
}
